tap "hamed-elfayome/claude-usage"
tap "homebrew/bundle"
tap "oven-sh/bun"
tap "peonping/tap"
brew "autojump"
brew "awscli"
brew "gh"
brew "git"
brew "git-filter-repo"
brew "jq"
brew "lazygit"
brew "neovim"
brew "go"
brew "volta"
brew "pnpm"
brew "python@3.13"
brew "ripgrep"
brew "zsh-syntax-highlighting"
brew "oven-sh/bun/bun"
brew "peonping/tap/peon-ping"
cask "1password", args: { appdir: "/Applications" }
cask "1password-cli"
cask "claude-code"
cask "hamed-elfayome/claude-usage/claude-usage-tracker"
cask "docker-desktop", args: { appdir: "/Applications" }
cask "firefox", args: { appdir: "/Applications" }
cask "font-fira-code", args: { appdir: "/Applications" }
cask "graphql-playground"
cask "hiddenbar", args: { appdir: "/Applications" }
cask "postman", args: { appdir: "/Applications" }
cask "rectangle", args: { appdir: "/Applications" }
cask "signal", args: { appdir: "/Applications" }
cask "slack", args: { appdir: "/Applications" }
cask "spotify", args: { appdir: "/Applications" }
cask "tableplus", args: { appdir: "/Applications" }
cask "visual-studio-code", args: { appdir: "/Applications" }
cask "warp"
cask "whatsapp", args: { appdir: "/Applications" }
vscode "anthropic.claude-code"
vscode "biomejs.biome"
vscode "dbaeumer.vscode-eslint"
vscode "docker.docker"
vscode "dracula-theme.theme-dracula"
vscode "eamodio.gitlens"
vscode "esbenp.prettier-vscode"
vscode "github.copilot-chat"
vscode "golang.go"
vscode "mikestead.dotenv"
vscode "ms-azuretools.vscode-containers"
vscode "ms-azuretools.vscode-docker"
vscode "vivaxy.vscode-conventional-commits"
vscode "wayou.vscode-todo-highlight"
vscode "wesbos.theme-cobalt2"
vscode "wix.vscode-import-cost"
vscode "yzhang.markdown-all-in-one"
